Fix/re 1867 birthdate picker
parti-renaissance/espace-adherent pull request #10132
Opened 2024-04-24 18:06 UTC by OverGlass

2024-04-24 18:06 UTC, victorcohenfr commented
Task linked: [RE-1867 Inscription BDE - Je veux renseigner ma date de naissance en mobile - Lorsque j'ouvre le choix du jour je ne peux pas scroll et descendre plus bas que le 4](https://app.clickup.com/t/2643737/RE-1867)

2024-04-26 11:20 UTC, ottaviano requested changes

2024-04-26 11:20 UTC, ottaviano commented on templates/security/besoindeurope_connect_magic_link.html.twig
> +    <form x-data x-init="$nextTick(function () {setTimeout(function () {}, 2000)})" action="{{ path('app_user_connect_with_magic_link', {app_domain: user_besoindeurope_host}) }}" method="POST" class=
il faut remettre l'action submit ici ?

2024-04-26 11:20 UTC, ottaviano commented on src/Controller/BesoinDEurope/Inscription/FurtherInformationController.php
> -use App\Adhesion\AdhesionStepEnum;
il faut remettre cet import ici

2024-04-26 17:48 UTC, ottaviano approved these changes

2024-04-29 08:11 UTC, merged