Add zones to /me
parti-renaissance/espace-adherent pull request #11042
Opened 2024-11-20 16:48 UTC by Remg

2024-11-20 16:55 UTC, OverGlass approved these changes
LGTM

2024-11-20 16:58 UTC, OverGlass requested changes
Les tests ne passent pas

2024-11-20 17:01 UTC, OverGlass approved these changes
LGTM

2024-11-21 13:48 UTC, ottaviano commented on src/Normalizer/AdherentNormalizer.php
> +        }
```suggestion
```

2024-11-21 13:48 UTC, ottaviano commented on features/api/user.feature
> +                    },
Could you add the code property for these two levels, please ?

2024-11-21 14:28 UTC, ottaviano approved these changes

2024-11-21 14:52 UTC, merged