[AdherentNotification] New membership counts
parti-renaissance/espace-adherent pull request #9189
Opened 2023-10-10 15:32 UTC by Remg

2023-11-02 14:11 UTC, tony-tran requested changes

2023-11-02 14:11 UTC, tony-tran commented on src/Command/SendNewMembershipNotificationCommand.php
> +    public function __construct(AdherentRepository $repository, MailerService $transactionalMailer)
Unuse $transactionalMailer

2023-11-24 09:19 UTC, tony-tran commented
Amazing job ! Congratz !

2023-11-28 18:10 UTC, ottaviano approved these changes

2023-11-28 19:01 UTC, merged